#!/usr/bin/env bash
# Phase 17-C — Observer Pathfinder apply script (idempotent, non-interactive).
# Target: Ubuntu 24.04 + Node 18 + PM2. Run on the Observer VPS as root.
set -Eeuo pipefail

OBSERVER_DIR="/root/genre-zenith/vps-agent/observer"
TARGET="services/playlistScraper.js"
PORT="3100"
HEALTH_URL="http://127.0.0.1:${PORT}/health"
SAMPLE_PLAYLIST_ID="37i9dQZF1DXcBWIGoYBM5M"
PLAYLIST_URL="http://127.0.0.1:${PORT}/playlists/${SAMPLE_PLAYLIST_ID}"

STAMP="$(date -u +%Y%m%d-%H%M%S)"
BACKUP=""

log()  { printf '\033[1;36m[17c]\033[0m %s\n' "$*"; }
ok()   { printf '\033[1;32m[17c]\033[0m %s\n' "$*"; }
err()  { printf '\033[1;31m[17c]\033[0m %s\n' "$*" >&2; }

restore_backup() {
  if [[ -n "$BACKUP" && -f "$BACKUP" ]]; then
    err "Restaurando backup: $BACKUP"
    cp -f "$BACKUP" "$TARGET"
    restart_observer || true
  fi
}

restart_observer() {
  if command -v pm2 >/dev/null 2>&1 && pm2 describe observer >/dev/null 2>&1; then
    log "pm2 restart observer"
    pm2 restart observer >/dev/null
  else
    log "PM2 não tem 'observer'. Matando porta ${PORT} e subindo via nohup."
    fuser -k "${PORT}/tcp" 2>/dev/null || true
    sleep 1
    nohup node server.js > observer.log 2>&1 &
    disown || true
  fi
}

trap 'rc=$?; if [[ $rc -ne 0 ]]; then err "Falha (exit=$rc). Tentando restaurar backup..."; restore_backup; fi' ERR

# 1. Localização
if [[ "$(pwd)" != "$OBSERVER_DIR" ]]; then
  if [[ -d "$OBSERVER_DIR" ]]; then
    cd "$OBSERVER_DIR"
    log "cd $OBSERVER_DIR"
  else
    err "Diretório $OBSERVER_DIR não existe."
    exit 2
  fi
fi

# 2. Pré-requisito
if [[ ! -f "$TARGET" ]]; then
  err "Arquivo $TARGET não existe em $(pwd). Abortando."
  exit 2
fi

# 3. Backup com timestamp
BACKUP="${TARGET}.pre17c-${STAMP}"
cp -f "$TARGET" "$BACKUP"
ok "Backup criado: $BACKUP"

# 4. Substituição (payload embutido em base64)
NEW_B64="LyoqCiAqIFBoYXNlIDE3LUMg4oCUIE9ic2VydmVyIC8gU3BvdGlmeSBQYXRoZmluZGVyIHNjcmFwZXIKICogLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tCiAqIFN1YnN0aXR1aSBjb21wbGV0YW1lbnRlIG8gc2NyYXBpbmcgZGUgRE9NLgogKiBGb250ZSDDum5pY2EgZGUgZGFkb3M6IHJlc3Bvc3RhIGRhIEFQSSBpbnRlcm5hCiAqICAgaHR0cHM6Ly9hcGktcGFydG5lci5zcG90aWZ5LmNvbS9wYXRoZmluZGVyL3YyL3F1ZXJ5CiAqIGN1am8gY29ycG8gY29udMOpbSBgZGF0YS5wbGF5bGlzdFYyLmNvbnRlbnQuaXRlbXNbXWAuCiAqCiAqIEVzdGEgZnVuw6fDo28gcmVjZWJlIHVtYSBgcGFnZWAgUGxheXdyaWdodCBqw6EgY29uZmlndXJhZGEgKGJyb3dzZXIuanMpCiAqIGUgcmV0b3JuYSBhIGVzdHJ1dHVyYSBub3JtYWxpemFkYSBkZSB1bWEgcGxheWxpc3QgcMO6YmxpY2EuCiAqCiAqIE7Do28gZmF6IGZhbGxiYWNrIHBhcmEgRE9NIOKAlCBzZSBvIFBhdGhmaW5kZXIgbsOjbyByZXNwb25kZXIgZGVudHJvCiAqIGRvIHRpbWVvdXQsIGEgZnVuw6fDo28gbGFuw6dhIGVycm8gZSBvIGNhbGxlciBkZWNpZGUgbyBxdWUgZmF6ZXIKICogKHJldHJ5LCBtYXJjYXIgNTAyLCBldGMpLgogKi8KCid1c2Ugc3RyaWN0JzsKCmNvbnN0IFBBVEhGSU5ERVJfSE9TVCA9ICdhcGktcGFydG5lci5zcG90aWZ5LmNvbSc7CmNvbnN0IFBBVEhGSU5ERVJfUEFUSCA9ICcvcGF0aGZpbmRlci92Mi9xdWVyeSc7CmNvbnN0IERFRkFVTFRfVElNRU9VVF9NUyA9IDI1XzAwMDsKCi8qKgogKiBAcGFyYW0ge2ltcG9ydCgncGxheXdyaWdodCcpLlBhZ2V9IHBhZ2UKICogQHBhcmFtIHtzdHJpbmd9IHBsYXlsaXN0SWQgIFNwb3RpZnkgcGxheWxpc3QgaWQgKGJhc2U2Miwgc2VtIHByZWZpeG8pLgogKiBAcGFyYW0ge3sgdGltZW91dE1zPzogbnVtYmVyLCB3YWl0Rm9ySWRsZU1zPzogbnVtYmVyIH19IFtvcHRzXQogKiBAcmV0dXJucyB7UHJvbWlzZTx7CiAqICAgcGxheWxpc3RfaWQ6IHN0cmluZywKICogICB1cmk6IHN0cmluZywKICogICBuYW1lOiBzdHJpbmd8bnVsbCwKICogICBkZXNjcmlwdGlvbjogc3RyaW5nfG51bGwsCiAqICAgb3duZXI6IHsgdXJpOiBzdHJpbmd8bnVsbCwgbmFtZTogc3RyaW5nfG51bGwgfXxudWxsLAogKiAgIGZvbGxvd2VyczogbnVtYmVyfG51bGwsCiAqICAgaW1hZ2VzOiBBcnJheTx7IHVybDogc3RyaW5nLCB3aWR0aDogbnVtYmVyfG51bGwsIGhlaWdodDogbnVtYmVyfG51bGwgfT4sCiAqICAgdG90YWxfdHJhY2tzOiBudW1iZXJ8bnVsbCwKICogICB0cmFja3M6IEFycmF5PE5vcm1hbGl6ZWRUcmFjaz4sCiAqICAgcmF3X3BhdGhmaW5kZXJfb3BlcmF0aW9uOiBzdHJpbmd8bnVsbCwKICogICBjYXB0dXJlZF9hdDogc3RyaW5nCiAqIH0+fQogKi8KYXN5bmMgZnVuY3Rpb24gc2NyYXBlUGxheWxpc3QocGFnZSwgcGxheWxpc3RJZCwgb3B0cyA9IHt9KSB7CiAgY29uc3QgdGltZW91dE1zID0gb3B0cy50aW1lb3V0TXMgPz8gREVGQVVMVF9USU1FT1VUX01TOwoKICBpZiAoIXBsYXlsaXN0SWQgfHwgdHlwZW9mIHBsYXlsaXN0SWQgIT09ICdzdHJpbmcnKSB7CiAgICB0aHJvdyBuZXcgRXJyb3IoJ3NjcmFwZVBsYXlsaXN0OiBwbGF5bGlzdElkIGlzIHJlcXVpcmVkJyk7CiAgfQoKICAvLyAxLiBSZWdpc3RyYSBsaXN0ZW5lciBBTlRFUyBkYSBuYXZlZ2HDp8OjbyBwYXJhIG7Do28gcGVyZGVyIGEgcmVzcG9zdGEuCiAgY29uc3QgcGF0aGZpbmRlckJvZGllcyA9IFtdOwogIGNvbnN0IG9uUmVzcG9uc2UgPSBhc3luYyAocmVzcG9uc2UpID0+IHsKICAgIHRyeSB7CiAgICAgIGNvbnN0IHVybCA9IHJlc3BvbnNlLnVybCgpOwogICAgICBpZiAoIXVybC5pbmNsdWRlcyhQQVRIRklOREVSX0hPU1QpKSByZXR1cm47CiAgICAgIGlmICghdXJsLmluY2x1ZGVzKFBBVEhGSU5ERVJfUEFUSCkpIHJldHVybjsKCiAgICAgIGNvbnN0IHN0YXR1cyA9IHJlc3BvbnNlLnN0YXR1cygpOwogICAgICBpZiAoc3RhdHVzIDwgMjAwIHx8IHN0YXR1cyA+PSAzMDApIHJldHVybjsKCiAgICAgIC8vIEFsZ3VtYXMgcmVzcG9zdGFzIGRvIFBhdGhmaW5kZXIgbsOjbyBzw6NvIEpTT04gKGV4OiAyMDQpLiBQcm90ZWdlLgogICAgICBjb25zdCBjdHlwZSA9IChyZXNwb25zZS5oZWFkZXJzKClbJ2NvbnRlbnQtdHlwZSddIHx8ICcnKS50b0xvd2VyQ2FzZSgpOwogICAgICBpZiAoIWN0eXBlLmluY2x1ZGVzKCdhcHBsaWNhdGlvbi9qc29uJykpIHJldHVybjsKCiAgICAgIGNvbnN0IGpzb24gPSBhd2FpdCByZXNwb25zZS5qc29uKCkuY2F0Y2goKCkgPT4gbnVsbCk7CiAgICAgIGlmICghanNvbikgcmV0dXJuOwoKICAgICAgLy8gTyBQYXRoZmluZGVyIHVzYSBtw7psdGlwbGFzIG9wZXJhw6fDtWVzIChmZXRjaFBsYXlsaXN0LCBmZXRjaFBsYXlsaXN0Q29udGVudHMsCiAgICAgIC8vIGhvbWUsIGV0YykuIFPDsyBub3MgaW50ZXJlc3NhIGEgcXVlIGNhcnJlZ2EgYGRhdGEucGxheWxpc3RWMmAuCiAgICAgIGNvbnN0IHB2MiA9IGpzb24/LmRhdGE/LnBsYXlsaXN0VjI7CiAgICAgIGlmICghcHYyKSByZXR1cm47CgogICAgICAvLyBPcGVyYXRpb24gbmFtZSB2ZW0gbm8gcXVlcnlzdHJpbmcgKD9vcGVyYXRpb25OYW1lPWZldGNoUGxheWxpc3TigKYpCiAgICAgIGxldCBvcGVyYXRpb25OYW1lID0gbnVsbDsKICAgICAgdHJ5IHsKICAgICAgICBjb25zdCB1ID0gbmV3IFVSTCh1cmwpOwogICAgICAgIG9wZXJhdGlvbk5hbWUgPSB1LnNlYXJjaFBhcmFtcy5nZXQoJ29wZXJhdGlvbk5hbWUnKTsKICAgICAgfSBjYXRjaCAoXykgeyAvKiBub29wICovIH0KCiAgICAgIHBhdGhmaW5kZXJCb2RpZXMucHVzaCh7IG9wZXJhdGlvbk5hbWUsIGJvZHk6IGpzb24gfSk7CiAgICB9IGNhdGNoIChfKSB7CiAgICAgIC8vIFNpbGVuY2lhIOKAlCBudW5jYSBxdWVyZW1vcyBkZXJydWJhciBvIHNjcmFwZXIgcG9yIHVtIGxpc3RlbmVyLgogICAgfQogIH07CiAgcGFnZS5vbigncmVzcG9uc2UnLCBvblJlc3BvbnNlKTsKCiAgbGV0IG5hdmlnYXRpb25FcnJvciA9IG51bGw7CiAgdHJ5IHsKICAgIC8vIDIuIE5hdmVnYSBwYXJhIGEgcMOhZ2luYSBww7pibGljYSBkYSBwbGF5bGlzdC4KICAgIGNvbnN0IHVybCA9IGBodHRwczovL29wZW4uc3BvdGlmeS5jb20vcGxheWxpc3QvJHtlbmNvZGVVUklDb21wb25lbnQocGxheWxpc3RJZCl9YDsKICAgIGF3YWl0IHBhZ2UuZ290byh1cmwsIHsgd2FpdFVudGlsOiAnZG9tY29udGVudGxvYWRlZCcsIHRpbWVvdXQ6IHRpbWVvdXRNcyB9KTsKCiAgICAvLyAzLiBFc3BlcmEgZXhwbGljaXRhbWVudGUgcG9yIHVtYSByZXNwb3N0YSBQYXRoZmluZGVyIGNvbSBgcGxheWxpc3RWMmAuCiAgICAvLyAgICBgd2FpdEZvclJlc3BvbnNlYCDDqSBtYWlzIHJvYnVzdG8gcXVlIGBzZXRUaW1lb3V0YCBwb2lzIHJlc29sdmUgYXNzaW0KICAgIC8vICAgIHF1ZSBvIHByZWRpY2F0ZSBiYXRlLgogICAgYXdhaXQgcGFnZS53YWl0Rm9yUmVzcG9uc2UoYXN5bmMgKHJlc3BvbnNlKSA9PiB7CiAgICAgIHRyeSB7CiAgICAgICAgY29uc3QgdSA9IHJlc3BvbnNlLnVybCgpOwogICAgICAgIGlmICghdS5pbmNsdWRlcyhQQVRIRklOREVSX0hPU1QpIHx8ICF1LmluY2x1ZGVzKFBBVEhGSU5ERVJfUEFUSCkpIHJldHVybiBmYWxzZTsKICAgICAgICBpZiAocmVzcG9uc2Uuc3RhdHVzKCkgIT09IDIwMCkgcmV0dXJuIGZhbHNlOwogICAgICAgIGNvbnN0IGN0eXBlID0gKHJlc3BvbnNlLmhlYWRlcnMoKVsnY29udGVudC10eXBlJ10gfHwgJycpLnRvTG93ZXJDYXNlKCk7CiAgICAgICAgaWYgKCFjdHlwZS5pbmNsdWRlcygnYXBwbGljYXRpb24vanNvbicpKSByZXR1cm4gZmFsc2U7CiAgICAgICAgY29uc3QganNvbiA9IGF3YWl0IHJlc3BvbnNlLmpzb24oKS5jYXRjaCgoKSA9PiBudWxsKTsKICAgICAgICByZXR1cm4gQm9vbGVhbihqc29uPy5kYXRhPy5wbGF5bGlzdFYyKTsKICAgICAgfSBjYXRjaCAoXykgewogICAgICAgIHJldHVybiBmYWxzZTsKICAgICAgfQogICAgfSwgeyB0aW1lb3V0OiB0aW1lb3V0TXMgfSk7CgogICAgLy8gUGVxdWVuYSBmb2xnYSBwYXJhIGNhcHR1cmFyIHJlc3Bvc3RhcyBhZGljaW9uYWlzIChwYWdpbmHDp8OjbyBpbmljaWFsCiAgICAvLyBjb3N0dW1hIHZpciBlbSAxLTIgY2hhbWFkYXMgc2VndWlkYXMgcGFyYSBgZmV0Y2hQbGF5bGlzdENvbnRlbnRzYCkuCiAgICBpZiAob3B0cy53YWl0Rm9ySWRsZU1zKSB7CiAgICAgIGF3YWl0IHBhZ2Uud2FpdEZvclRpbWVvdXQob3B0cy53YWl0Rm9ySWRsZU1zKTsKICAgIH0gZWxzZSB7CiAgICAgIGF3YWl0IHBhZ2Uud2FpdEZvckxvYWRTdGF0ZSgnbmV0d29ya2lkbGUnLCB7IHRpbWVvdXQ6IDVfMDAwIH0pLmNhdGNoKCgpID0+IHt9KTsKICAgIH0KICB9IGNhdGNoIChlcnIpIHsKICAgIG5hdmlnYXRpb25FcnJvciA9IGVycjsKICB9IGZpbmFsbHkgewogICAgcGFnZS5vZmYoJ3Jlc3BvbnNlJywgb25SZXNwb25zZSk7CiAgfQoKICBpZiAocGF0aGZpbmRlckJvZGllcy5sZW5ndGggPT09IDApIHsKICAgIGNvbnN0IHJlYXNvbiA9IG5hdmlnYXRpb25FcnJvciA/IGAgKCR7bmF2aWdhdGlvbkVycm9yLm1lc3NhZ2V9KWAgOiAnJzsKICAgIHRocm93IG5ldyBFcnJvcihgUGF0aGZpbmRlciByZXNwb25zZSB3aXRoIHBsYXlsaXN0VjIgbm90IGNhcHR1cmVkIGZvciAke3BsYXlsaXN0SWR9JHtyZWFzb259YCk7CiAgfQoKICAvLyA0LiBFc2NvbGhlIGEgbWVsaG9yIHJlc3Bvc3RhOiBwcmlvcml6YSBhIHF1ZSB0ZW0gbWFpcyBpdGVtcyBjYXB0dXJhZG9zCiAgLy8gICAgZSBjdWpvIGBwbGF5bGlzdFYyLnVyaWAgYmF0ZSBjb20gbyBwbGF5bGlzdElkIHBlZGlkby4KICBjb25zdCBiZXN0ID0gcGlja0Jlc3RQYXRoZmluZGVyQm9keShwYXRoZmluZGVyQm9kaWVzLCBwbGF5bGlzdElkKTsKICBpZiAoIWJlc3QpIHsKICAgIHRocm93IG5ldyBFcnJvcihgTm8gUGF0aGZpbmRlciBib2R5IG1hdGNoZWQgcGxheWxpc3QgJHtwbGF5bGlzdElkfWApOwogIH0KCiAgLy8gNS4gTm9ybWFsaXphIGUgcmV0b3JuYS4KICByZXR1cm4gbm9ybWFsaXplUGxheWxpc3QoYmVzdC5ib2R5LCBwbGF5bGlzdElkLCBiZXN0Lm9wZXJhdGlvbk5hbWUpOwp9CgovLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KLy8gSGVscGVycwovLyAtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0KCmZ1bmN0aW9uIHBpY2tCZXN0UGF0aGZpbmRlckJvZHkoY2FuZGlkYXRlcywgcGxheWxpc3RJZCkgewogIGxldCBiZXN0ID0gbnVsbDsKICBsZXQgYmVzdFNjb3JlID0gLTE7CiAgZm9yIChjb25zdCBjIG9mIGNhbmRpZGF0ZXMpIHsKICAgIGNvbnN0IHB2MiA9IGMuYm9keT8uZGF0YT8ucGxheWxpc3RWMjsKICAgIGlmICghcHYyKSBjb250aW51ZTsKICAgIGNvbnN0IGl0ZW1zID0gcHYyPy5jb250ZW50Py5pdGVtczsKICAgIGNvbnN0IGl0ZW1Db3VudCA9IEFycmF5LmlzQXJyYXkoaXRlbXMpID8gaXRlbXMubGVuZ3RoIDogMDsKICAgIGNvbnN0IHVyaU1hdGNoZXMgPSB0eXBlb2YgcHYyPy51cmkgPT09ICdzdHJpbmcnCiAgICAgICYmIHB2Mi51cmkuZW5kc1dpdGgoYDoke3BsYXlsaXN0SWR9YCk7CiAgICAvLyBTY29yZTogMTAwMCBwb250b3MgcG9yIHVyaSBiYXRlciArIDEgcG9yIGl0ZW0gY2FwdHVyYWRvLgogICAgY29uc3Qgc2NvcmUgPSAodXJpTWF0Y2hlcyA/IDEwMDAgOiAwKSArIGl0ZW1Db3VudDsKICAgIGlmIChzY29yZSA+IGJlc3RTY29yZSkgewogICAgICBiZXN0U2NvcmUgPSBzY29yZTsKICAgICAgYmVzdCA9IGM7CiAgICB9CiAgfQogIHJldHVybiBiZXN0Owp9CgpmdW5jdGlvbiBub3JtYWxpemVQbGF5bGlzdChib2R5LCBwbGF5bGlzdElkLCBvcGVyYXRpb25OYW1lKSB7CiAgY29uc3QgcHYyID0gYm9keT8uZGF0YT8ucGxheWxpc3RWMiA/PyB7fTsKICBjb25zdCBpdGVtcyA9IEFycmF5LmlzQXJyYXkocHYyPy5jb250ZW50Py5pdGVtcykgPyBwdjIuY29udGVudC5pdGVtcyA6IFtdOwoKICBjb25zdCB0cmFja3MgPSBpdGVtcwogICAgLm1hcCgoaXRlbSwgaWR4KSA9PiBub3JtYWxpemVUcmFjayhpdGVtLCBpZHgpKQogICAgLmZpbHRlcihCb29sZWFuKTsKCiAgcmV0dXJuIHsKICAgIHBsYXlsaXN0X2lkOiBwbGF5bGlzdElkLAogICAgdXJpOiB0eXBlb2YgcHYyLnVyaSA9PT0gJ3N0cmluZycgPyBwdjIudXJpIDogYHNwb3RpZnk6cGxheWxpc3Q6JHtwbGF5bGlzdElkfWAsCiAgICBuYW1lOiBwaWNrU3RyaW5nKHB2Mi5uYW1lKSwKICAgIGRlc2NyaXB0aW9uOiBwaWNrU3RyaW5nKHB2Mi5kZXNjcmlwdGlvbiksCiAgICBvd25lcjogbm9ybWFsaXplT3duZXIocHYyLm93bmVyVjIgPz8gcHYyLm93bmVyKSwKICAgIGZvbGxvd2VyczogcGlja051bWJlcihwdjI/LmZvbGxvd2VycyA/PyBwdjI/LmZvbGxvd2VyQ291bnQpLAogICAgaW1hZ2VzOiBub3JtYWxpemVJbWFnZXMocHYyPy5pbWFnZXM/Lml0ZW1zID8/IHB2Mj8uaW1hZ2VzID8/IFtdKSwKICAgIHRvdGFsX3RyYWNrczogcGlja051bWJlcihwdjI/LmNvbnRlbnQ/LnRvdGFsQ291bnQpLAogICAgdHJhY2tzLAogICAgcmF3X3BhdGhmaW5kZXJfb3BlcmF0aW9uOiBvcGVyYXRpb25OYW1lLAogICAgY2FwdHVyZWRfYXQ6IG5ldyBEYXRlKCkudG9JU09TdHJpbmcoKSwKICB9Owp9CgpmdW5jdGlvbiBub3JtYWxpemVUcmFjayhpdGVtLCBpZHgpIHsKICAvLyBQYXRoZmluZGVyIHVzYSBgaXRlbVYyLmRhdGFgIGNvbW8gc291cmNlLW9mLXRydXRoIHBhcmEgYSBmYWl4YS4KICBjb25zdCB2MiA9IGl0ZW0/Lml0ZW1WMj8uZGF0YSA/PyBudWxsOwogIGlmICghdjIpIHJldHVybiBudWxsOwoKICBjb25zdCB1cmkgPSBwaWNrU3RyaW5nKHYyLnVyaSkgPz8gbnVsbDsKICBjb25zdCB0cmFja0lkID0gdXJpICYmIHVyaS5zdGFydHNXaXRoKCdzcG90aWZ5OnRyYWNrOicpID8gdXJpLnNsaWNlKCdzcG90aWZ5OnRyYWNrOicubGVuZ3RoKSA6IG51bGw7CgogIGNvbnN0IGFsYnVtID0gdjIuYWxidW1PZlRyYWNrID8/IG51bGw7CiAgY29uc3QgYWxidW1VcmkgPSBwaWNrU3RyaW5nKGFsYnVtPy51cmkpID8/IG51bGw7CiAgY29uc3QgYWxidW1Db3ZlciA9IHBpY2tBbGJ1bUNvdmVyKGFsYnVtPy5jb3ZlckFydD8uc291cmNlcyA/PyBhbGJ1bT8uY292ZXJBcnQgPz8gbnVsbCk7CgogIGNvbnN0IGFydGlzdHNJdGVtcyA9IEFycmF5LmlzQXJyYXkoYWxidW0/LmFydGlzdHM/Lml0ZW1zKQogICAgPyBhbGJ1bS5hcnRpc3RzLml0ZW1zCiAgICA6IEFycmF5LmlzQXJyYXkodjI/LmFydGlzdHM/Lml0ZW1zKQogICAgICA/IHYyLmFydGlzdHMuaXRlbXMKICAgICAgOiBbXTsKCiAgY29uc3QgYXJ0aXN0cyA9IGFydGlzdHNJdGVtcy5tYXAoKGEpID0+ICh7CiAgICBuYW1lOiBwaWNrU3RyaW5nKGE/LnByb2ZpbGU/Lm5hbWUpID8/IHBpY2tTdHJpbmcoYT8ubmFtZSkgPz8gbnVsbCwKICAgIHVyaTogcGlja1N0cmluZyhhPy51cmkpID8/IG51bGwsCiAgfSkpLmZpbHRlcigoYSkgPT4gYS5uYW1lIHx8IGEudXJpKTsKCiAgcmV0dXJuIHsKICAgIHBvc2l0aW9uOiB0eXBlb2YgaXRlbT8udWlkID09PSAnc3RyaW5nJyA/IGlkeCArIDEgOiBpZHggKyAxLAogICAgdHJhY2tfaWQ6IHRyYWNrSWQsCiAgICB1cmksCiAgICBuYW1lOiBwaWNrU3RyaW5nKHYyLm5hbWUpID8/IG51bGwsCiAgICBwbGF5Y291bnQ6IHBpY2tOdW1iZXIodjIucGxheWNvdW50KSwKICAgIGR1cmF0aW9uX21zOiBwaWNrTnVtYmVyKHYyPy50cmFja0R1cmF0aW9uPy50b3RhbE1pbGxpc2Vjb25kcyksCiAgICBleHBsaWNpdDogZGVyaXZlRXhwbGljaXQodjI/LmNvbnRlbnRSYXRpbmcpLAogICAgYWxidW06IHsKICAgICAgbmFtZTogcGlja1N0cmluZyhhbGJ1bT8ubmFtZSkgPz8gbnVsbCwKICAgICAgdXJpOiBhbGJ1bVVyaSwKICAgICAgY292ZXI6IGFsYnVtQ292ZXIsCiAgICB9LAogICAgYXJ0aXN0cywKICB9Owp9CgpmdW5jdGlvbiBub3JtYWxpemVPd25lcihvd25lcikgewogIGlmICghb3duZXIgfHwgdHlwZW9mIG93bmVyICE9PSAnb2JqZWN0JykgcmV0dXJuIG51bGw7CiAgcmV0dXJuIHsKICAgIHVyaTogcGlja1N0cmluZyhvd25lci51cmkpID8/IG51bGwsCiAgICBuYW1lOiBwaWNrU3RyaW5nKG93bmVyPy5kYXRhPy5uYW1lKSA/PyBwaWNrU3RyaW5nKG93bmVyPy5uYW1lKSA/PyBwaWNrU3RyaW5nKG93bmVyPy51c2VybmFtZSkgPz8gbnVsbCwKICB9Owp9CgpmdW5jdGlvbiBub3JtYWxpemVJbWFnZXMocmF3KSB7CiAgY29uc3QgbGlzdCA9IEFycmF5LmlzQXJyYXkocmF3KSA/IHJhdyA6IFtdOwogIGNvbnN0IG91dCA9IFtdOwogIGZvciAoY29uc3QgZW50cnkgb2YgbGlzdCkgewogICAgLy8gUG9kZSB2aXIgY29tbyB7IHNvdXJjZXM6IFsuLi5dIH0gb3UgasOhIGNvbW8gc291cmNlLgogICAgY29uc3Qgc291cmNlcyA9IEFycmF5LmlzQXJyYXkoZW50cnk/LnNvdXJjZXMpID8gZW50cnkuc291cmNlcyA6IFtlbnRyeV07CiAgICBmb3IgKGNvbnN0IHMgb2Ygc291cmNlcykgewogICAgICBjb25zdCB1cmwgPSBwaWNrU3RyaW5nKHM/LnVybCk7CiAgICAgIGlmICghdXJsKSBjb250aW51ZTsKICAgICAgb3V0LnB1c2goewogICAgICAgIHVybCwKICAgICAgICB3aWR0aDogcGlja051bWJlcihzPy53aWR0aCksCiAgICAgICAgaGVpZ2h0OiBwaWNrTnVtYmVyKHM/LmhlaWdodCksCiAgICAgIH0pOwogICAgfQogIH0KICByZXR1cm4gb3V0Owp9CgpmdW5jdGlvbiBwaWNrQWxidW1Db3Zlcihzb3VyY2VzKSB7CiAgaWYgKCFzb3VyY2VzKSByZXR1cm4gbnVsbDsKICBjb25zdCBsaXN0ID0gQXJyYXkuaXNBcnJheShzb3VyY2VzKSA/IHNvdXJjZXMgOiBBcnJheS5pc0FycmF5KHNvdXJjZXM/LnNvdXJjZXMpID8gc291cmNlcy5zb3VyY2VzIDogW107CiAgaWYgKGxpc3QubGVuZ3RoID09PSAwKSByZXR1cm4gbnVsbDsKICAvLyBQcmVmZXJpbW9zIGEgbWFpb3IsIG1hcyBzZSBuw6NvIGhvdXZlciB3aWR0aCB1c2Ftb3MgYSBwcmltZWlyYS4KICBsZXQgYmVzdCA9IG51bGw7CiAgZm9yIChjb25zdCBzIG9mIGxpc3QpIHsKICAgIGNvbnN0IHVybCA9IHBpY2tTdHJpbmcocz8udXJsKTsKICAgIGlmICghdXJsKSBjb250aW51ZTsKICAgIGlmICghYmVzdCkgeyBiZXN0ID0gczsgY29udGludWU7IH0KICAgIGNvbnN0IHN3ID0gcGlja051bWJlcihzPy53aWR0aCkgPz8gMDsKICAgIGNvbnN0IGJ3ID0gcGlja051bWJlcihiZXN0Py53aWR0aCkgPz8gMDsKICAgIGlmIChzdyA+IGJ3KSBiZXN0ID0gczsKICB9CiAgcmV0dXJuIGJlc3QgPyBwaWNrU3RyaW5nKGJlc3QudXJsKSA/PyBudWxsIDogbnVsbDsKfQoKZnVuY3Rpb24gZGVyaXZlRXhwbGljaXQoY29udGVudFJhdGluZykgewogIGlmICghY29udGVudFJhdGluZykgcmV0dXJuIG51bGw7CiAgY29uc3QgbGFiZWwgPSBwaWNrU3RyaW5nKGNvbnRlbnRSYXRpbmc/LmxhYmVsKTsKICBpZiAoIWxhYmVsKSByZXR1cm4gbnVsbDsKICByZXR1cm4gbGFiZWwudG9VcHBlckNhc2UoKSA9PT0gJ0VYUExJQ0lUJzsKfQoKZnVuY3Rpb24gcGlja1N0cmluZyh2KSB7CiAgcmV0dXJuIHR5cGVvZiB2ID09PSAnc3RyaW5nJyAmJiB2Lmxlbmd0aCA+IDAgPyB2IDogbnVsbDsKfQoKZnVuY3Rpb24gcGlja051bWJlcih2KSB7CiAgaWYgKHR5cGVvZiB2ID09PSAnbnVtYmVyJyAmJiBOdW1iZXIuaXNGaW5pdGUodikpIHJldHVybiB2OwogIGlmICh0eXBlb2YgdiA9PT0gJ3N0cmluZycgJiYgdi50cmltKCkgIT09ICcnICYmIE51bWJlci5pc0Zpbml0ZShOdW1iZXIodikpKSByZXR1cm4gTnVtYmVyKHYpOwogIHJldHVybiBudWxsOwp9Cgptb2R1bGUuZXhwb3J0cyA9IHsgc2NyYXBlUGxheWxpc3QgfTsK"

NEW_HASH="$(printf '%s' "$NEW_B64" | base64 -d | sha256sum | awk '{print $1}')"
CUR_HASH="$(sha256sum "$TARGET" | awk '{print $1}')"

if [[ "$NEW_HASH" == "$CUR_HASH" ]]; then
  log "Conteúdo já está na versão 17-C (hash idêntico). Pulando reescrita."
else
  TMP="$(mktemp)"
  printf '%s' "$NEW_B64" | base64 -d > "$TMP"
  mv -f "$TMP" "$TARGET"
  ok "playlistScraper.js substituído."
fi

# 5. Sintaxe
log "node --check $TARGET"
if ! node --check "$TARGET"; then
  err "Sintaxe inválida no novo scraper. Restaurando backup."
  cp -f "$BACKUP" "$TARGET"
  exit 3
fi
ok "Sintaxe OK."

# 6. Restart
restart_observer

# 7. Espera
log "Aguardando 3s para o servidor subir..."
sleep 3

# 8. /health
log "GET $HEALTH_URL"
if ! HEALTH_BODY="$(curl -fsS --max-time 10 "$HEALTH_URL")"; then
  err "Falha em /health. Restaurando backup."
  restore_backup
  exit 4
fi
ok "/health respondeu: $(printf '%s' "$HEALTH_BODY" | head -c 200)"

# 9. /playlists/:id
log "GET $PLAYLIST_URL"
if ! PLAYLIST_BODY="$(curl -fsS --max-time 60 "$PLAYLIST_URL")"; then
  err "Falha em $PLAYLIST_URL. Restaurando backup."
  restore_backup
  exit 5
fi

# 10. Validação dos campos no primeiro track via Node (sem depender de jq)
log "Validando contrato do primeiro track..."
VALIDATION="$(node -e '
  let raw = "";
  process.stdin.on("data", c => raw += c);
  process.stdin.on("end", () => {
    let j;
    try { j = JSON.parse(raw); } catch (e) {
      console.error("JSON inválido:", e.message); process.exit(10);
    }
    const tracks = Array.isArray(j.tracks) ? j.tracks : null;
    if (!tracks || tracks.length === 0) {
      console.error("Resposta não contém tracks[]"); process.exit(11);
    }
    const t = tracks[0];
    const required = ["playcount","duration_ms","album","artists","uri","track_id"];
    const missing = required.filter(k => !(k in t) || t[k] === null || t[k] === undefined);
    if (missing.length) {
      console.error("Campos ausentes no primeiro track:", missing.join(", "));
      console.error("Sample keys:", Object.keys(t).join(","));
      process.exit(12);
    }
    if (typeof t.album !== "object" || !t.album)            { console.error("album não é objeto"); process.exit(13); }
    if (!Array.isArray(t.artists) || t.artists.length === 0){ console.error("artists vazio");      process.exit(14); }
    console.log("OK first track:", JSON.stringify({
      track_id: t.track_id, uri: t.uri, name: t.name,
      playcount: t.playcount, duration_ms: t.duration_ms,
      album_name: t.album.name, artists: t.artists.map(a=>a.name)
    }));
  });
' <<<"$PLAYLIST_BODY")" || {
  err "Validação do primeiro track falhou. Restaurando backup."
  err "$VALIDATION"
  restore_backup
  exit 6
}

ok "$VALIDATION"

trap - ERR
ok "✅ Phase 17-C aplicada com sucesso."
